# Generated by Django 4.0.4 on 2024-03-21 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment_app', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='add_profile',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagefile/'),
        ),
    ]
