# Generated by Django 4.0.4 on 2024-03-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0003_rename_profile_add_profile_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='equipment_images/')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('priceday', models.IntegerField(blank=True, null=True)),
                ('pricehour', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
