# Generated by Django 4.0.4 on 2024-03-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0004_equipments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='specification',
            new_name='spec',
        ),
    ]
