# Generated by Django 4.0.4 on 2024-03-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0005_rename_description_product_desc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipments',
        ),
    ]
