# Generated by Django 5.0 on 2024-04-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0008_testi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testi',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
